name: Release

on:
  push:
    branches:
      - main
    paths:
      - "Containerfile"
      - "torrc*"
      - "run.sh"

jobs:
  build_and_push_latest:
    name: Build and Push 'latest' image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push 'latest' image
        uses: docker/build-push-action@v6
        with:
          file: ./Containerfile
          no-cache: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/tor-relay:latest